"""
File: packages/shared/git_utils.py
Layer: Shared / Utilities / GitOps
Purpose: Enforces standardization across all Git artifacts created by autonomous agents.
Problem Solved: Prevents messy commit histories and inconsistent PR titles by applying 'Conventional Commits' logic.
Interaction: Used by Fixer and Jules agents when preparing data for the GitHubService.
Dependencies: datetime, os
Inputs: Action type, description, and incident ID
Outputs: Standardized commit and PR title strings
"""
import os
from datetime import datetime

def generate_sre_commit_message(action_type: str, description: str, incident_id: str = None) -> str:
    """
    Generates a standardized commit message for SRE agents.
    Follows Conventional Commits style to ensure clean repo history.
    
    Args:
        action_type (str): The nature of the change (e.g. 'remediation').
        description (str): A human-readable summary of the fix.
        incident_id (str, optional): The associated incident tracking number.
    Returns:
        str: A multi-line commit message with audit metadata.
    """
    if not description or description in ["[title]", "title"]:
        description = f"Autonomous remediation for {action_type}"
    
    ref = f" | Ref: #{incident_id}" if incident_id else ""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    return f"fix(agent-{action_type}): {description}{ref}\n\nGenerated by SRE Autonomous Engine at {timestamp}"

def generate_sre_pr_title(service: str, action: str) -> str:
    """
    Generates a descriptive and consistent PR title for the SRE squad.
    
    Args:
        service (str): The name of the target service.
        action (str): The specific operation performed.
    Returns:
        str: A categorized PR title.
    """
    if not service: service = "system"
    if not action or action == "[title]": action = "reliability-patch"
    
    return f"feat({service}): SRE Autonomous {action.title()} [Auto-Heal]"
