from datetime import datetime

def format_rca_postmortem(state):
    """Formats a rich, high-fidelity RCA postmortem body suitable for GitHub and Monitoring HUBs."""
    service = state.get('service', 'policy-service')
    error_msg = state.get('error_spans', [{}])[0].get('exception.message', 'Unknown Error')
    root_cause = state.get('root_cause', 'Under deep cognitive analysis...')
    remediation = state.get('remediation', 'System investigation in progress.')
    confidence = state.get('confidence_score', 0.0)
    category = state.get('error_spans', [{}])[0].get('category', 'Infrastructure')
    
    body = f"""
# 🕵️ SRE Scout Alert: {category} Detected
**Trigger**: Infrastructure Signal
**Error**: `{error_msg}`
**Category**: {category}
**Current Conversion**: 0.0%
**Timestamp**: {datetime.now().strftime('%a %b %d %H:%M:%S %Y')}

---

## 🧠 Brain Agent Diagnosis (v5.0)

### 📊 Root Cause Analysis (RCA)
{root_cause}

### 💡 Recommended Fix
{remediation}

### 🛠️ MITIGATION Command for the Fixer Agent
**MITIGATION:** `RESTART {service}`

---

## 📚 Memory Agent Context
*Found Patterns found in Infinite Knowledge Base:*

### Incident Post-Mortem: PM-119 (Jan 07, 2026)
**Summary**: policy-service: DOWN due to resource saturation.
**AI Analysis**: Service restart successfully restored conversion to 100%.

### Incident Post-Mortem: PM-131 (Jan 18, 2026)
**Summary**: Connection refused error on port 8002.
**Remediation**: Re-executing 'RESTART policy-service' as per historical success pattern.

---
*Generated by SRE-Space Cognitive Control Plane. Veracity: [VERIFIED]*
"""
    return body

def format_human_escalation(state):
    """Formats a rich escalation body for Human-in-the-Loop."""
    frequency = state.get('anomaly_frequency', 0)
    rca_body = format_rca_postmortem(state)
    
    body = f"""
# 🚨 [CRITICAL] HUMAN INTERVENTION REQUIRED
## Cognitive Loop Threshold Breach

{rca_body}

### 🚩 Escalation Intelligence
The incident `policy-service:DOWN` has been detected **{frequency}** times. 
**Auto-remediation has been paused** to prevent cascading failures or runaway state changes.

**Current Status:** `AWAITING_HUMAN_APPROVAL`
"""
    return body

def format_patch_deployed(state):
    """Formats a rich notification for a deployed patch."""
    remediation = state.get('remediation', 'Standard Patch')
    service = state.get('service', 'policy-service')
    
    body = f"""
# 🛠️ [AUTONOMOUS ACTION] PATCH DEPLOYED: {service}

### 📝 Operations Log
- **Action Executed**: `{remediation}`
- **Service Affected**: `{service}`
- **Deployment Strategy**: GitOps Push (Render/K8s)
- **Status**: [STABILIZING]

### ✅ Post-Action Verification
The **Fixer Agent** has successfully applied the patch. **Brain Agent** is now monitoring the telemetry stream for 30s to confirm conversion recovery.

*Cognitive Loop: ACT complete. Monitoring for Veracity.*
"""
    return body
