from datetime import datetime

def format_rca_postmortem(state):
    """Formats a rich RCA postmortem body suitable for GitHub issues."""
    service = state.get('service', 'Unknown Service')
    error_msg = state.get('error_spans', [{}])[0].get('exception.message', 'No error message available')
    root_cause = state.get('root_cause', 'Under investigation')
    remediation = state.get('remediation', 'Manual intervention required')
    confidence = state.get('confidence_score', 0.0)
    
    body = f"""
## 🧠 Brain Agent Diagnosis

### 1. Root Cause Analysis (RCA)
{root_cause}

**Key Indicators:**
- **Service:** `{service}`
- **Error:** `{error_msg}`
- **Confidence Score:** `{confidence:.2f}`

### 2. Recommended Fix
{remediation}

### 3. MITIGATION command for the Fixer Agent
- **MITIGATION:** RESTART `{service}` (or appropriate action based on RCA)

---
*This incident report was automatically generated by the SRE-Space Cognitive Engine v3.5.*
*Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""
    return body

def format_human_escalation(state):
    """Formats a rich escalation body for Human-in-the-Loop."""
    frequency = state.get('anomaly_frequency', 0)
    rca_body = format_rca_postmortem(state)
    
    body = f"""
# 🚨 HUMAN INTERVENTION REQUIRED

{rca_body}

### 🚩 Escalation Reason
Issue detected **{frequency}** times in the last hour. Auto-remediation has been paused to prevent cascading failures or runaway loops.

**Status:** AWAITING MANUAL REVIEW
"""
    return body

def format_patch_deployed(state):
    """Formats a rich notification for a deployed patch."""
    remediation = state.get('remediation', 'Standard Patch')
    service = state.get('service', 'System')
    
    body = f"""
# 🛠️ PATCH DEPLOYED: {service}

### 📝 Action Details
**Action Executed:** `{remediation}`
**Service:** `{service}`
**Namespace:** `{state.get('namespace', 'N/A')}`

### ✅ Verification
The patch has been successfully applied and verified against current metrics. The service is monitoring for stability.

*Automated Remediation Cycle Complete.*
"""
    return body
