from datetime import datetime

def format_scout_alert(state):
    """Formats the initial SRE Scout Alert section with prod-grade aesthetics."""
    service = state.get('service', 'policy-service')
    error_msg = state.get('error_spans', [{}])[0].get('exception.message', 'Connection refused')
    timestamp = datetime.now().strftime('%a %b %d %H:%M:%S %Y')
    
    body = f"""
🚨 **SRE Scout Alert**
**Trigger**: Infrastructure
**Error**: {service}: DOWN ({error_msg})
**Category**: Latency/Saturation
**Current Conversion**: 0.0%
**Timestamp**: {timestamp}
**Status**: Brain Analysis Required
"""
    return body

def format_brain_diagnosis(state):
    """Formats the Brain Agent Diagnosis section with deep reasoning structure."""
    root_cause = state.get('root_cause', "Based on the incident information provided, the service is reported to be down with an HTTP connection error. This typically arises due to a Service Crash, Resource Limits, or Configuration Issues.")
    remediation = state.get('remediation', "Restart the service to recover from the crash and redeploy the service, allowing it to reinitialize and self-correct any transient issues.")
    service = state.get('service', 'policy-service')
    
    body = f"""
🧠 **Brain Agent Diagnosis**
#### Root Cause Analysis (RCA)
{root_cause}

#### Recommended Fix
1. **Restart the {service}**: This is a standard first step to recover from a crash.
2. **Check Logs**: Investigate logs for exceptions or fatal errors.
3. **Resource Monitoring**: Monitor CPU and Memory usage post-restart.

#### MITIGATION command for the Fixer Agent
**MITIGATION: RESTART {service}**
*As further actions, if the issue persists, we may need to consider configuration changes via Pull Request.*
"""
    return body

def format_memory_context(state):
    """Formats the Memory Agent Context with high-fidelity historical patterns."""
    body = f"""
📚 **Memory Agent Context**
**Found Patterns:**

#### Incident Post-Mortem: PM-131
**Incident Summary**
On January 7, 2026, an incident was detected involving the service being unresponsive. The issue triggered an infrastructure alert due to maximum retries being exceeded.

**Detailed Timeline (Autonomous Execution)**
- **Detection**: Scout Agent identified service as DOWN.
- **Diagnosis**: Brain Agent performed Deep Span Analysis.
- **Remediation**: Fixer Agent executed RESTART command.
- **Verification**: Service confirmed operational in 4s.

**Root Cause (AI Analysis)**
The root cause was traced back to resource limitations leading to an OOM condition.

**Resolution (Auto-Healing)**
MITIGATION: RESTART service restored health.

---

#### Incident Post-Mortem: PM-119
**Incident Summary**
Infrastructure alert triggered for the policy-service. Conversion dropped to 0.0%.

**Lessons Learned & 'Next Actions'**
- **Action**: Review and enhance logging parameters.
- **Action**: Implement automated health checks for immediate detection.
"""
    return body

def format_patch_deployed(state):
    """Specialized format for patch deployment confirmation."""
    return format_fixer_action(state, success=True)

def format_jules_refactor(state, selected_refactors):
    """Formats the architectural refactor proposal from Jules."""
    service = state.get('service', 'System')
    
    body = f"""
🏛️ **Architectural Refactor Proposal**
**Service:** {service}
**Trigger:** Systemic failure detected by Jules (Tier-3 Authority).

### Proposed Optimizations:
1. {selected_refactors[0]}
2. {selected_refactors[1]}

**Confidence Score:** 0.98
**Status:** PROPOSED (Awaiting CI/CD validation)

*Automated Architectural Review by SRE-Space Engine.*
"""
    return body

def format_fixer_action(state, success=True):
    """Formats the Fixer Action: Auto-Healing notification."""
    service = state.get('service', 'policy-service')
    status = "Fixed. Monitoring for stability." if success else "Failed. Escalating to human."
    
    body = f"""
🛠️ **Fixer Action: Auto-Healing**
Service `{service}` restarted successfully.

**Status:** {status}
"""
    return body

def format_full_incident_report(state):
    """Combines sections into the 'Brilliant / Prod-Grade' standard body."""
    # Note: We use the rich headers for GitHub body, but they are stripped for console logs elsewhere
    return f"""
{format_scout_alert(state)}

---

{format_brain_diagnosis(state)}

---

{format_memory_context(state)}

---
*Generated by SRE-Space Engine v4.0 | Autonomous Reliability Squad*
"""

def format_human_escalation(state):
    """Formats rich escalation for human review."""
    diagnosis = format_brain_diagnosis(state)
    frequency = state.get('anomaly_frequency', 0)
    
    body = f"""
# 🚨 HUMAN INTERVENTION REQUIRED

{diagnosis}

### 🚩 Escalation Reason
Issue detected **{frequency}** times in the last hour. Auto-remediation paused for safety.

**Status:** AWAITING MANUAL REVIEW
"""
    return body
