version: '3.8'

services:
  # --- EVENT BUS (KAFKA KRAFT) ---
  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0

  # --- OBSERVABILITY ---
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317" # OTLP gRPC
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4318:4318" # OTLP http
    environment:
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
    depends_on:
      - jaeger

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/chroma/data

  # --- MICROSERVICES ---
  quote-service:
    build:
      context: ..
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    ports:
      - "8001:8001"
    depends_on:
      - kafka

  policy-service:
    build:
      context: ..
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    ports:
      - "8002:8002"
    depends_on:
      - kafka

  user-service:
    build:
      context: ..
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    ports:
      - "8003:8003"
    depends_on:
      - kafka

  frontend:
    build:
      context: ../dashboard
    ports:
      - "3001:80"
    depends_on:
      - quote-service
      - policy-service

  # --- AGENT CONTROL PLANE ---
  agent-scout:
    build:
      context: ..
    environment:
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - kafka

  agent-brain:
    build:
      context: ..
    env_file: ../.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - otel-collector

  agent-memory:
    build:
      context: ..
    env_file: ../.env
    depends_on:
      - chromadb

  agent-fixer:
    build:
      context: ..
    env_file: ../.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - agent-brain

volumes:
  chroma-data:
