version: '3.8'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-config.yaml"]
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
    environment:
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # UI
      - "14268"
      - "14250"

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/chroma/chroma

  scout:
    build:
      context: ../agents/scout
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - otel-collector

  brain:
    build:
      context: ../agents/brain
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
    depends_on:
      - chromadb

  memory:
    build:
      context: ../agents/memory
    environment:
      - CHROMA_DB_HOST=chromadb
      - CHROMA_DB_PORT=8000
    depends_on:
      - chromadb

  fixer:
    build:
      context: ../agents/fixer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}

volumes:
  chroma-data:
