import os
from datetime import datetime

def generate_sre_commit_message(action_type, description, incident_id=None):
    """
    Generates a standardized commit message for SRE agents.
    Enforces Conventional Commits style and prevents [title] placeholders.
    """
    if not description or description == "[title]" or description == "title":
        description = f"Autonomous remediation for {action_type}"
    
    ref = f" | Ref: #{incident_id}" if incident_id else ""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    return f"fix(agent-{action_type}): {description}{ref}\n\nGenerated by SRE Autonomous Engine at {timestamp}"

def generate_sre_pr_title(service, action):
    """Generates a clean PR title for GitHub."""
    if not service: service = "system"
    if not action or action == "[title]": action = "reliability-patch"
    
    return f"feat({service}): SRE Autonomous {action.title()} [Auto-Heal]"
